version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  fs_db:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      
  mysqldb:
    image: mysql:5.7
    env_file: .env

  cassandradb:
    image: dina/ala-cassandra:v0.1

  biocacheservice:
    image: dina/ala-biocacheservice:v0.1
    depends_on:
      - cassandradb
      - solr
    links:
      - cassandradb
      - solr
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  biocachehub:
    image: dina/ala-biocachehub:v0.1
    depends_on:
      - biocacheservice
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  collectory:
    image: dina/ala-collectory:v0.1
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  webserver:
    image: dina/ala-nginx:v0.1
    environment:
      - VIRTUAL_HOST=gbifsweden.se,uptime.gbifsweden.se
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - ghost
      - uptime

  ndex:
    image: dina/ala-nameindex:v0.1
    command: /bin/ash

  biocachebackend:
    image: dina/ala-biocachebackend:v0.1
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - cassandradb
      - solr
    command: /bin/ash

  solr:
    image: dina/ala-solrindex:v0.1

  mongo:
    image: mvertes/alpine-mongo

  uptime:
    image: usman/docker-uptime
    links:
      - mongo:mongodb
    volumes:
      - ./uptime/default.yaml:/tmp/uptime/config/default.yaml

  ghost:
    image: zzrot/alpine-ghost
    container_name: ghost    
    environment:
      PROD_DOMAIN: http://gbifsweden.se
      NODE_ENV: production
    volumes:
      - ./ghost/content:/var/lib/ghost

  ghost-backup:
    image: bennetimo/ghost-backup
    container_name: ghost-backup
    volumes_from:
      - ghost
    volumes:
      - ./ghost/backups:/backups