version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  fs_db:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      
  db:
    image: mysql:5.7
    env_file: .env

  cas:
    image: dina/ala-cassandra:v0.1

  as:
    image: dina/ala-tomcat:v0.1
    environment:
      - VIRTUAL_HOST=ala.local
    depends_on:
      - db
      - cas
    links:
      - db
      - cas

  ws:
    image: nginx

  ndex:
    image: dina/ala-nameindex:v0.1   

  solr:
    image: dina/ala-solrindex:v0.1

  mongo:
    image: mongo

  uptime:
    image: usman/docker-uptime
    ports:
      - 8082:8082
    links:
      - mongo:mongodb
      - ghost

  ghost: 
    image: ghost
    volumes:
      - ./ghost:/tmp
    ports:
      - 2368:2368
