version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  fs_db:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: fs_volume

  mysqldb:
    image: mysql:5.7
    env_file: .env
    container_name: mysqldb

  cassandradb:
    image: dina/ala-cassandra:v0.1
    container_name: cassandradb

  biocacheservice:
    image: dina/ala-biocacheservice:v0.1
    container_name: biocacheservice
    depends_on:
      - cassandradb
      - solr
    links:
      - cassandradb
      - solr
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  biocachehub:
    image: dina/ala-biocachehub:v0.1
    container_name: biocachehub
    depends_on:
      - biocacheservice
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  collectory:
    image: dina/ala-collectory:v0.1
    container_name: collectory
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      JAVA_OPTS: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true

  webserver:
    image: dina/ala-nginx:v0.1
    container_name: testgbif.nrm.se
    environment:
      - VIRTUAL_HOST=testgbif.nrm.se,uptime.testgbif.nrm.se
      - DNSDOCK_ALIAS=testgbif.nrm.se
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - ghost
      - uptime

  ndex:
    image: dina/ala-nameindex:v0.1
    command: /bin/ash
    container_name: nameindex

  biocachebackend:
    image: dina/ala-biocachebackend:v0.1
    container_name: biocachebackend
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - cassandradb
      - solr
    command: /bin/ash

  solr:
    image: dina/ala-solrindex:v0.1
    container_name: solr

  mongo:
    image: dina/ala-mongo:v0.1
    #image: mvertes/alpine-mongo
    container_name: mongo

  uptime:
    image: usman/docker-uptime
    container_name: uptime
    links:
      - mongo:mongodb
    volumes:
      - ./uptime/default.yaml:/tmp/uptime/config/default.yaml

  ghost:
    image: zzrot/alpine-ghost
    container_name: ghost
    environment:
      PROD_DOMAIN: http://testgbif.nrm.se
      NODE_ENV: production
    volumes:
      - ./ghost/content:/var/lib/ghost

  ghost-backup:
    image: bennetimo/ghost-backup
    container_name: ghost-backup
    volumes_from:
      - ghost
    volumes:
      - ./ghost/backups:/backups

  dnsdock:
    image: aacebedo/dnsdock:v1.15.0-amd64
    container_name: dnsserver
    ports:
      - 172.17.0.1:53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
