version: '2'

services:

  fs:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./cassandra-datadir:/var/lib/cassandra
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data:/data

  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306:3306
    volumes_from:
      - fs

#  ddb:
#    image: cassandra
#    env_file: .env
#    volumes_from:
#      - fs

  ws:
    image: nginx
    depends_on:
      - as
    links:
      - as

  as:
    build: tomcat/.
    ports:
      - 8080:8080
    links:
      - db
