version: '2'

services:

  fs_db:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
<<<<<<< HEAD
      
  fs_ddb:
    image: tianon/true
    volumes:      
      - ./cassandra-datadir:/data      
      
=======
      #- ./cassandra-datadir:/data/cassandra

>>>>>>> 9d56105718888bc145cbd92f4b8b15b8729c8110
  db:
    image: mysql:5.7
    env_file: .env
    volumes_from:
      - fs_db
    ports:
      - 3306:3306 

  ddb:
    build: cassandra/.    
    volumes_from:
      - fs_ddb
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160 

  ws:
    image: nginx
    depends_on:
      - as
    links:
      - as

  as:
    build: tomcat/.
    ports:
      - 8080:8080
    links:
      - db
