version: '3'

services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    container_name: dnsmasq
    command: --log-facility=- --server=127.0.0.11 --server=193.10.57.11 --server=8.8.8.8 --server=172.16.0.72 --server=172.16.0.7 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add:
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:bioatlas.se

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      #- ./nginx-proxy-certs:/etc/nginx/certs:ro
      - ./nginx-proxy/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf

  webserver:
    image: nginx:alpine
    container_name: webserver
    environment:
      - VIRTUAL_HOST=bioatlas.se
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - wordpress
      - loggerservice
      - imageservice
      - imagestore
    volumes:
      #- ./env/.htpasswd:/etc/nginx/htpasswd
      - ./webserver/app.conf:/etc/nginx/conf.d/app.conf:ro

  mysqldb:
    image: mysql:5.7
    env_file: ./env/.envcollectory
    container_name: mysqldb
    volumes:
      - db_data_collectory:/var/lib/mysql

  cassandradb:
    image: cassandra:3.11.2
    container_name: cassandradb
    volumes:
      - ./cassandra3/entrypoint-wrap.sh:/entrypoint-wrap.sh:z
      - ./cassandra3/biocache-db/cassandra3-schema.txt:/docker-entrypoint-initdb.d/cassandra3-schema.cql
      - ./cassandra3/cassandra-files/cassandra-env.sh:/tmp/cassandra-env.sh
      - ./cassandra3/cassandra-files/cassandra.yaml:/tmp/cassandra.yaml
      - db_data_cassandra:/var/lib/cassandra
    entrypoint: /bin/bash -c "cp /tmp/cassandra.yaml /etc/cassandra/cassandra.yaml && cp /tmp/cassandra-env.sh /etc/cassandra/cassandra-env.sh && /entrypoint-wrap.sh"

  biocacheservice:
    image: bioatlas/ala-biocacheservice:v0.2
    container_name: biocacheservice
    depends_on:
      - cassandradb
      - solr
    links:
      - cassandradb
      - solr
    environment:
      JAVA_OPTS: -Xmx2g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    volumes:
      - data_nameindex:/data/lucene/namematching
      - ./config/biocache-config.properties:/data/biocache/config/biocache-config.properties:ro
      - ./config/logger-client.properties:/data/logger-client/config/logger-client.properties:ro

  biocachehub:
    image: bioatlas/ala-biocachehub:v0.2
    container_name: biocachehub
    depends_on:
      - biocacheservice
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/ala-hub-config.properties:/data/ala-hub/config/ala-hub-config.properties:ro

  collectory:
    image: bioatlas/ala-collectory:v0.2
    container_name: collectory
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    env_file: ./env/.envcollectory
    volumes:
      - ./config/ala-collectory-config.properties:/tmp/ala-collectory-config.properties:ro
    command: /bin/ash -c "envsubst < /tmp/ala-collectory-config.properties > /data/ala-collectory/config/ala-collectory-config.properties && catalina.sh run"

  nameindex:
    image: bioatlas/ala-nameindex:v0.2
    command: /bin/ash
    container_name: nameindex
    volumes:
      - data_nameindex:/data/lucene/namematching

  biocachebackend:
    image: bioatlas/ala-biocachebackend:v0.2
    container_name: biocachebackend
    links:
      - biocachehub
      - biocacheservice
      - collectory
      - cassandradb
      - solr
    command: /bin/ash
    environment:
      biocache_opts: -Xmx1g -Xms256m
    volumes:
      - data_nameindex:/data/lucene/namematching
      - data_biocachebackend:/data
      - ./config/blacklistMediaUrls.txt:/data/biocache/config/blacklistMediaUrls.txt
      - ./config/biocache-config.properties:/data/biocache/config/biocache-config.properties:ro

  solr:
    image: solr:7.3-alpine
    container_name: solr
    environment:
      SOLR_HEAP: 4g
    volumes:
      - ./solr7/mycores:/opt/solr/server/solr/mycores
      - ./solr7/solr.xml:/opt/solr/server/solr/solr.xml
      - ./solr7/zoo.cfg:/opt/solr/server/solr/zoo.cfg
      - ./solr7/lib/jts-core-1.15.0.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.15.0.jar
      - ./solr7/solr.in.sh:/etc/default/solr.in.sh:ro
      - data_solr:/opt/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - biocache
      - bie
      - bie-offline
    ports:
      - 8983:8983

  loggerservice:
    image: bioatlas/ala-loggerservice:v0.2
    container_name: loggerservice
    depends_on:
      - mysqldblogger
    links:
      - mysqldblogger
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    env_file: ./env/.envlogger
    volumes:
      - ./config/logger-config.properties:/tmp/logger-config.properties:ro
    command: /bin/ash -c "envsubst < /tmp/logger-config.properties > /data/logger/config/logger-config.properties && catalina.sh run"

  mysqldblogger:
    image: mysql:5.7
    env_file: ./env/.envlogger
    container_name: mysqldblogger
    volumes:
      - ./loggerservice/db:/docker-entrypoint-initdb.d
      - db_data_loggerservice:/var/lib/mysql

  imageservice:
    image: bioatlas/ala-imageservice:v0.2
    container_name: imageservice
    depends_on:
      - psqldbimage
    links:
      - psqldbimage
    environment:
      JAVA_OPTS: -Xmx2g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    env_file: ./env/.envimage
    volumes:
      - ./config/images-config.properties:/tmp/images-config.properties
      - data_images:/data/images/store
      - data_images_elasticsearch:/data/images/elasticsearch
    command: /bin/ash -c "envsubst < /tmp/images-config.properties > /data/images/config/images-config.properties && catalina.sh run"

  static:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html
    container_name: static

  imagestore:
    image: bioatlas/ala-imagestore:v0.2
    volumes:
      - data_images:/data/images/store
    container_name: imagestore

  psqldbimage:
    image: postgres:9.6.8-alpine
    env_file: ./env/.envimage
    container_name: psqldbimage
    volumes:
      - db_data_imageservice:/var/lib/postgresql/data

  apiservice:
    image: bioatlas/ala-api:v0.2
    container_name: apiservice
    depends_on:
      - mysqldbapi
    links:
      - mysqldbapi
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    env_file: ./env/.envapi
    volumes:
      - ./config/webapi-config.properties:/tmp/webapi-config.properties:ro
    command: /bin/ash -c "envsubst < /tmp/webapi-config.properties > /data/webapi/config/webapi-config.properties && catalina.sh run"

  mysqldbapi:
    image: mysql:5.7
    env_file: ./env/.envapi
    container_name: mysqldbapi
    volumes:
      - db_data_apiservice:/var/lib/mysql

  mysqldbwordpress:
    image: mysql:5.7
    container_name: mysqldbwordpress
    env_file: ./env/.envwordpress
    volumes:
      - db_data_wordpress:/var/lib/mysql

  wordpress:
    image: wordpress:4.9.5-apache
    container_name: wordpress
    ports:
      - 8080:80
    env_file: ./env/.envwordpress
    volumes:
      - ./wordpress/themes/atlas/bioatlas-wordpress-theme-master:/var/www/html/wp-content/themes/atlas
      - ./wordpress/wp-config-sample.php:/usr/src/wordpress/wp-config-sample.php:ro

  specieslists:
    image: bioatlas/ala-specieslists:v0.2
    container_name: specieslists
    links:
      - mysqldbspecieslist
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    env_file: ./env/.envspecieslists
    volumes:
      - ./config/specieslist-webapp-config.properties:/tmp/specieslist-webapp-config.properties:ro
      - data_nameindex:/data/lucene/namematching
    command: /bin/ash -c "envsubst < /tmp/specieslist-webapp-config.properties > /data/specieslist-webapp/config/specieslist-webapp-config.properties && catalina.sh run"

  mysqldbspecieslist:
    image: mysql:5.7
    env_file: ./env/.envspecieslists
    container_name: mysqldbspecieslist
    command: --sql_mode=""
    volumes:
      - ./specieslists/db:/docker-entrypoint-initdb.d
      - db_data_specieslists:/var/lib/mysql

  bieindex:
    image: bioatlas/ala-bieindex:v0.2
    container_name: bieindex
    environment:
      JAVA_OPTS: -Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/bie-index-config.properties:/data/bie-index/config/bie-index-config.properties:ro

  biehub:
    image: bioatlas/ala-biehub:v0.2
    container_name: biehub
    environment:
      - JAVA_OPTS=-Xmx1g -Xms256m -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/ala-bie-config.properties:/data/ala-bie/config/ala-bie-config.properties:ro

volumes:
  db_data_collectory:
  db_data_cassandra:
  db_data_loggerservice:
  db_data_imageservice:
  db_data_apiservice:
  data_nameindex:
  data_images:
  data_biocachebackend:
  data_solr:
  data_images_elasticsearch:
  db_data_wordpress:
  db_data_specieslists:
